package com.yj.yjesjd.config;

public class Test {
    public static void main(String[] args) {
//        String s = "GGRGGRRGGGRRGRRRGGRGGRRRGGRRGRR";
//        for (int j = 6; j <= 12; j++) {
//
//            int time = 1;
//            while (time != 0) {
//                time--;
//                StringBuilder sb = new StringBuilder();
//                for (int i = 1; i < s.length() + 1; i++) {
//                    if (i % 2 == 0) sb.append(s.charAt(i - 1));
//                    else {
//                        sb.append('G');
//                        sb.append(s.charAt(i - 1));
//                        sb.append('R');
//                    }
//                }
//                s = sb.toString();
//            }
//            System.out.println(j+"  "+s.length()+"===>"+s);
//        }
        System.out.println(buildingHouse("12").length()
                +buildingHouse("12"));
    }
    //String s = "GGRGGRRGGGRRGRRRGGRGGRRRGGRRGRR";
    static String buildingHouse(String n) {

        if(n.equals("1")) return"R";
        if(n.equals("2")) return "GRR";
        if(n.equals("3")) return "GGRRGRR";
        if(n.equals("4")) return "GGRGGRRGGGRRGRR";
        if(n.equals("5")) return "GGRGGRRGGGRRGRRRGGRGGRRRGGRRGRR";
        if(n.equals("6")) return "GGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRR";
        if(n.equals("7")) return "GGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRR";
        if(n.equals("8")) return "GGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRR";
        if(n.equals("9")) return "GGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRR";
        if(n.equals("10")) return "GGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRR";
        if(n.equals("11")) return "GGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRR";
        if(n.equals("12")) return "GGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRR";
        else if(isNum(n)) return"N";
        else if(Integer.parseInt(n)>12||Integer.parseInt(n)<1) return "O";
        else return null;

    }
    public  static boolean isNum(String s ){
        for (int i = 0; i <s.length() ; i++) {
            if(!Character.isDigit(s.charAt(i)))return  true;
        }
        return false;
    }

}